### ISSUE TITLE
Feature Request: Better handling of Image Boundaries and Seamless Tiling

### ISSUE THREAD

**Issue by bbbbbr** [bbbbbr/gimp-plugin-pixel-art-scalers#3]
_Originally posted by @nightmaredream in https://github.com/bbbbbr/gimp-plugin-pixel-art-scalers/issues/2#issuecomment-560049665_

About "seamless" processing... 

And about "pixels stuck to sides" on semi-transparent images...

I'll show you an example of side stuck upscale pixels.
![witherwart](https://user-images.githubusercontent.com/33467930/69909055-e08ad700-13c2-11ea-93db-bae6434e40f0.png)

The left mushroom thing's topmost part is squared, that's because the upscale process bounces to borders...

It would be difficult to difference different jobs, so separating seamless batch from no-repeat batch would allow to do, in one batch, save borders.. And in the other batch... Emulate seamlessness with copies of the tiles in every directions and then reduce back to original size. 

But yeah, for the moment, a tolerance slider... Then making every tolerated pixels fully opaque!

> Seamlessness examples
> 
> ![coarse_dirt_silty](https://user-images.githubusercontent.com/33467930/69909138-6ce9c980-13c4-11ea-88e3-db63def71b78.png)
> 
> ![image](https://user-images.githubusercontent.com/33467930/69909149-b1756500-13c4-11ea-8cfd-bca3b70b0dc4.png)
> 
> ![seamlessresult](https://user-images.githubusercontent.com/33467930/69909161-cfdb6080-13c4-11ea-9148-6b4cdc702190.png)
> 
> While it's still a very nice result, seamlessness is broken.
> 
> Another example: (Very good, but broken seamlessness)
> ![image](https://user-images.githubusercontent.com/33467930/69909180-234dae80-13c5-11ea-801b-7636fb95900a.png)

**Comment by bbbbbr** [comment]
Can you attach the source images for the other two examples? (mushroom, second seamless tile)

**Comment by nightmaredream** [comment]
The archive can be downloaded from here, so rights are attributed to the right group.
https://dokucraft.co.uk/stash/?mod-support-downloader
And the file is this: 
[1.12.2-BiomesOPlenty.zip](https://github.com/bbbbbr/gimp-plugin-pixel-art-scalers/files/3908771/1.12.2-BiomesOPlenty.zip)
You might even find the intention to add batch support to your amazing plugin... But it would need to be ran standalone i assume... Unless you make a gimp command that loads in an entire folder without the files necessarily being opened inside gimp. 
So, the two files are: 
![witherwart](https://user-images.githubusercontent.com/33467930/69920980-06b08580-145c-11ea-9742-bbc06a8c6846.png)
![pine_log](https://user-images.githubusercontent.com/33467930/69920985-0fa15700-145c-11ea-8dac-16138f418420.png)

**Comment by nightmaredream** [comment]
Basically, 16x16 textures are extracted from the main minecraft's jar, so to turn them 128x128 is quite a process. Building resource packs from scratch is done with Resource PAck Workbench. I upscaled the default textures and i created my own textures where needed. It's meant to be a pack that adapts over any packs. Mods have their own textures and "Resource Pack Workbench" extracts them as well. They're jar files which are archives that contains all sorts of stuff, java stuff, class files, and textures. 
Resource packs attempts to put nicer textures than default on top of the default game.
Upscaling therefor is really sweet and that's where tiling and hard borders comes really in a handy. 
I used a similar method with the game Super Mario Bros X, which is a fangame similar to mario maker. But i did it pixel by pixel! By hand! That's why a nice upscale plugin is co much better! 
And what you did there is just amazing.
Thought... With tiling and all, it'll be much perfect. 

SMBX example skin https://www.supermariobrosx.org/forums/viewtopic.php?t=508

**Comment by nightmaredream** [comment]
All right, i just figured out about the thread separation. I'll test latest build right now. 

Tested! 

All right! So indeed, tolerred pixels are made opaque entirely! That's fabulous! :D 

![image](https://user-images.githubusercontent.com/33467930/70003617-b60b5c00-1531-11ea-8d2a-93f06213286a.png)

**Comment by bbbbbr** [comment]
The seamless tile and edge handling features seem useful and worth investigating. 

While the theoretical solutions for them are not complicated (so far as I can tell now) the actual work to do it is going to be harder. The processing pipeline needs to be reorganized and it's not clear how that will go.

**Comment by nightmaredream** [comment]
Border pixels could have a certain importance, also, some files comes in pair, like, some bushes have an upper part and a bottom part which connects together. So without breaking the over all pixel shape, side pixels could somehow give the first wave toward inner and inner and more. MAking sure border pixels are safe will ensure that for as long as the original low pixel image is seamless, the upscaled one would also keep the same character. 

Edge handling would help tiling, and also help rounder objects. ... I guess it could have parameters to pre set for the task user has in mind, whether it'S to tile or to have nice and round objects at edges when an image isn't tiled...

There's a complicated reasoning from there. 

The way edge pixels are handled would differ indeed whether a texture is either no-repeat or tiled. If it's tiled, it needs borders that keeps some pretty much straight pixels and even inspire from pixels at opposite border. 
But in the opposite case, instead of srenghtening the border rows and columns of pixels, it would have to be somewhat the next pixel to border that would be prioritized. Hence... That mushroom guy thingie there, if border pixels would tend to push to next pixel to first pixel border, then, the final result would be rounder. 

Batching, i assume, like i said before, is best done by separating tasks in different folders... 

The script that would make seamless could also have -x, -y, x and y checkboxes so it puts accent on all borders or only certain borders.

That's about what i believe would make something pretty complete in the end.

Batching folders would be like: 
Batch1: no-repeat pngs
Batch2: all-direction-seamless
batch3: Top-only
Batch4: Bottom-only
Batch5: Both-top-bottom
Batch6:Both-Left-Right... 
And so on...

It would get complicated after a while... But that'S just in case it's really necessary. 

Hope you figure something out anyways. 

![image](https://user-images.githubusercontent.com/33467930/70021410-a9512d00-155e-11ea-8e0c-931ea5c5bbce.png)

Directions, up, down, left, right, could be independent. Each could either be:
1:Tile, no-tile,
2: Push: none, exterior, to center.
3:Solidify border, Solidify toward center, solidify none...

So.. Upward could be tile, sides and bottom, no-tile... For example.

This way, it would be well organized and still simple.

**Comment by nightmaredream** [comment]
Hi, i thought about something: Custom upscale/downscale where 100% is "no change to scale" and 0% makes an 1x1px image... For whatever reason a user would like an average of all colors of an image. And maximum could be quite high. Also... When it gets quite high, some other process could be added that are similar to Gimp's "Dilate/Erode" so details be more, or less slim. 
It would be so nice if Gimp had a decent batch system in it.
I imagined it would have been nice if you would've got a hand on open source generic filters that could be added in the process to give character to the upscaled image, right into the process... But then i thought.... As you'Re developing tiling and it's inverse, it makes a unique feature that wouldn,t be accessible from outside. For example... Imagine i would use an hypothetic new gimp batch that truly can align multiple filters one next to another and use any filter it has, even downloaded plug-ins. 
I would make normal maps, but gimp isn't seamless. Krita is.
https://www.youtube.com/watch?v=9ICGks0-InQ
Its wraparound tool is really awesome...
Gimp seems to have frozen in time while Krita is so brand new. 
Anyways...
What if you could literally make a series of process from external filters Inside your own plugin? That would so much simplify any batching, but furthermore, that would give virtually any gimp feature in the upscale process... Imagine if it had even layering... Imagine if it produced an XCF and a PNG and that the XCF contained all the final layers produced through the batch...
Dayom...
That's so further away than just "now". 

When i want to give character to an upscale, normally, with XNview, which isn't that good and lacks so many features Gimp and Your plugin has, what i do is i make multiple versions with different noise, different blur, some with bloom... Then i combine images... But doing that with gimp with an automation made with "tinytask" can take hours and the exporting is really slow because gimp has to load dialogs which is time consuming. 

Every recorded actions are done for every filename_layer_XYZ all combined into one file in a "result" folder that i have to access everytime with the cursor automation. I made many layers in those examples that i created before learning about your Amazing plugin.


Made with XNview (before i learned about your plugin)
![algae](https://user-images.githubusercontent.com/33467930/70094402-72c3f280-15f0-11ea-9fca-07f4173b24be.png)
![amber_block](https://user-images.githubusercontent.com/33467930/70094403-72c3f280-15f0-11ea-8cf6-47ed923038b1.png)
![amber_ore](https://user-images.githubusercontent.com/33467930/70094404-72c3f280-15f0-11ea-9c5d-092b59fb6817.png)

After performing some layer tasks with gimp and "TinyTask". https://www.tinytask.net/

![amber_block_resultat](https://user-images.githubusercontent.com/33467930/70094474-9424de80-15f0-11ea-8fb6-c943dfb0c72f.png)
![amber_ore_resultat](https://user-images.githubusercontent.com/33467930/70094475-9424de80-15f0-11ea-95eb-4883dbcc49ce.png)
![algae_resultat](https://user-images.githubusercontent.com/33467930/70094476-94bd7500-15f0-11ea-9e3b-c28f556124a4.png)


Final result, after multiple passes and many, many folders with each many copies of the same images, but with small different details...
![amber_block](https://user-images.githubusercontent.com/33467930/70094544-bae31500-15f0-11ea-83db-89b387d07ffd.png)
![amber_ore](https://user-images.githubusercontent.com/33467930/70094545-bae31500-15f0-11ea-9192-2abf1dd36076.png)
![algae](https://user-images.githubusercontent.com/33467930/70094547-bae31500-15f0-11ea-8207-a642c3546cd6.png)

And while i produced these files with automation with the base files from biomes - o - plenty, with xnview and gimp, i had that automation to export a png first, but save an xcf file right after.

[xcf3.zip](https://github.com/bbbbbr/gimp-plugin-pixel-art-scalers/files/3918970/xcf3.zip)

So... If all those process could all be done in a pre-defined process, it would be so much simpler.

While, your plugin could use generic filters, layering, in order to not only upscale, but also give character to the image produced, but only by user efforts. 

By the way... You're doing great stuff, have you got a patreon? i can'T monthly sub, but i sure can donate a bit, or something.

**Comment by bbbbbr** [comment]
I've added a couple border/edge handling options. Not all the permutations, but some of the more likely to be used ones while also keeping the UI and processing work within a reasonable limit.

Here is a build. Unless there are problems I'll soon check them in and tag it as a release.
[plugin_pixel_art_scalers_2019_dec_07_001.zip](https://github.com/bbbbbr/gimp-plugin-pixel-art-scalers/files/3935892/plugin_pixel_art_scalers_2019_dec_07_001.zip)

I suspect some of the capabilities you are looking for could be scripted using Python with GIMP. Based on the documentation it looks like it is very powerful (close to the capabilities of C/C++ plugins), and may also be able to call other plugins such as this one and pass them controlling parameters.

Sources of possible interest:
https://alessandrofrancesconi.it/projects/bimp/
https://github.com/jfmdev/PythonFuSamples

**Comment by nightmaredream** [comment]
Awesome, well, if that can inspire you for a new plugin in your arsenal, that would be very sweet! I'm a coding potato to be honest, but i'm a much better artist! I'll give a go to your current release! IT's amazing, thanx for your amazing work! 

I tried Bimp, tho i believe it lacks many features, it seems to only use some built in filters and nothing else. But i might have missed something.  Might be it! I'll give it a second go and study in deeper depths!

I'll try more tomorrow, thought i wonder if individual directions would be better than horizontal and vertical? 
For example, say i want padding on top but... Not tile, but solifiied border at bottom...

Example 
![image](https://user-images.githubusercontent.com/33467930/70387228-69c87d80-1970-11ea-897b-16a0a879e694.png)
Anyway, your approach is also relevant, but for corner tiles, it becomes more tricky. But...Well... At a certain point, most of the job is done by the plugin, a few details can be refined by hand and that's part of the reel!

**Comment by nightmaredream** [comment]
Hi, i thought about a very important feature, and somebody else asked for it on a texture making discussiion group. 

The feature is to optionally keep transparent regions square. so predefined UV unwraps doesn't go on top of unwanted transparent pixels.

An easy way of doing this is to merge upscaled image on top of the original image through the process.

**Comment by bbbbbr** [comment]
These are good ideas. However, some of them are outside the scope of the current work (perhaps in the future), or outside the scope of this plugin. 

It is too bad that gimp doesn't have a good macro recording and playback feature (I think one exists, but it may not be able to call non-core plugins?). It seems like it could help with some of these cases.

**Comment by nightmaredream** [comment]
Well, the feature to keep transparent regions square is really important for converting Dokucraft to high resolution. But it's easier to simply keep original and produce upscale on top of the original in this case.
Anyways, you did some awesome work! thanx for that! 

It's important for entities because they depend on very straight UV.

**Comment by nightmaredream** [comment]
Hi, i just figured out that in certain context, upscaling stripe sequences, in this case, vertical, causes the result image to be truncated, sometimes it works okay, sometimes it doesn't and makes a cropped image....Example: 
![image](https://user-images.githubusercontent.com/33467930/71061085-3e464f80-2135-11ea-9584-ca9c800103ed.png)
Original file:
![image](https://user-images.githubusercontent.com/33467930/71061212-8bc2bc80-2135-11ea-82a7-2750f2768945.png)
And when it doesn't fail... It does what's expected:
![image](https://user-images.githubusercontent.com/33467930/71061248-9a10d880-2135-11ea-9c13-c63bd4f2bb96.png)

Oh... Images lost transparency through copy-paste but that's no big deal, it's about the cropped portion only.

**Comment by bbbbbr** [comment]
Have you tried an updated build after the fix for the following was checked in?

Final scaled image size is incorrect (cropped) :https://github.com/bbbbbr/gimp-plugin-pixel-art-scalers/issues/5

**Comment by nightmaredream** [comment]
Oh, you just made me aware of that update! I subscribed to your project so i never miss an update again! :)  Thank you! :) And make a patreon, not that i can afford it, but people who loves your work could, on their behalf!
